# Generated by Django 4.2.2 on 2023-06-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_historical_figures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historical_figures",
            name="image_url",
            field=models.URLField(max_length=500),
        ),
    ]
