# Generated by Django 4.2.2 on 2023-06-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_historical_figures_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historical_figures",
            name="image_url",
            field=models.URLField(),
        ),
    ]
