# Generated by Django 4.2.2 on 2023-06-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_historical_figures_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="historical_figures",
            name="chosen",
            field=models.BooleanField(default=False),
        ),
    ]
