# Generated by Django 4.2.2 on 2023-06-30 00:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_historical_figures_chosen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historical_figures",
            name="chosen",
        ),
    ]
